import { discoverComponents } from './services/discovery';
import { validateRSNT } from './services/validation';
import { BASIC_RULES } from './rules/basic-rules';
import { renderRSNT, applyConstraints } from './services/rendering';

/**
 * Main logic for the Figma Plugin
 */

// Show the UI when the plugin runs
figma.showUI(__html__, { width: 440, height: 700, themeColors: true });

/**
 * Handle messages from the UI
 */
figma.ui.onmessage = async (msg) => {

  // 1. Generate (or Force Generate) new design elements
  if (msg.type === 'generate' || msg.type === 'generate-force') {
    const { intent, rsnt: providedRSNT } = msg;

    try {
      // Step A: Load mappings
      figma.ui.postMessage({ type: 'status', status: 'loading', message: 'Preparing environment...' });
      const savedMappings = figma.root.getPluginData('component-mappings');
      const mappings = savedMappings ? JSON.parse(savedMappings) : {};

      let rsnt;

      if (msg.type === 'generate-force' && providedRSNT) {
        rsnt = providedRSNT;
        figma.ui.postMessage({ type: 'status', status: 'loading', message: 'Force rendering design...' });
      } else if (msg.type === 'generate' && providedRSNT) {
        // Use the RSNT already generated by the UI thread
        rsnt = providedRSNT;

        // Step C: Validation (unless forced)
        figma.ui.postMessage({ type: 'status', status: 'loading', message: 'Running design safety checks...' });
        const validationResult = validateRSNT(rsnt, BASIC_RULES);

        if (!validationResult.valid) {
          figma.ui.postMessage({
            type: 'validation-error',
            message: validationResult.errors.length > 0
              ? 'Design rules violations detected.'
              : 'Design has warnings.',
            errors: validationResult.errors,
            warnings: validationResult.warnings,
            rsnt
          });
          return;
        }
      } else {
        throw new Error('MISSING_DATA: No RSNT data received from UI.');
      }

      // Step D: Rendering
      figma.ui.postMessage({ type: 'status', status: 'loading', message: 'Applying design to Figma canvas...' });
      const createdNode = await renderRSNT(rsnt, mappings);

      figma.currentPage.appendChild(createdNode);
      applyConstraints(createdNode, rsnt.constraints);

      figma.currentPage.selection = [createdNode];
      figma.viewport.scrollAndZoomIntoView([createdNode]);

      figma.ui.postMessage({
        type: 'complete',
        message: `✓ Generated ${rsnt.semanticRole}!`
      });

    } catch (error: any) {
      console.error('Workflow failed:', error);
      figma.ui.postMessage({
        type: 'error',
        message: error.message || 'An unexpected error occurred.'
      });
    }
  }

  // 2. Discover existing components (Manual trigger)
  if (msg.type === 'discover') {
    try {
      figma.ui.postMessage({ type: 'status', status: 'loading', message: 'Scanning file...' });
      const inventory = await discoverComponents();
      figma.ui.postMessage({
        type: 'complete',
        message: `✓ Found ${inventory.components.length} components.`,
        data: inventory
      });
    } catch (error: any) {
      figma.ui.postMessage({ type: 'error', message: `Discovery failed: ${error.message}` });
    }
  }

  // 3. Save component mappings
  if (msg.type === 'save-mappings') {
    try {
      figma.root.setPluginData('component-mappings', JSON.stringify(msg.mappings));
      figma.ui.postMessage({ type: 'complete', message: '✓ Mappings saved!' });
    } catch (error: any) {
      figma.ui.postMessage({ type: 'error', message: `Save failed: ${error.message}` });
    }
  }

  // 4. Load mappings
  if (msg.type === 'load-mappings') {
    const saved = figma.root.getPluginData('component-mappings');
    figma.ui.postMessage({
      type: 'mappings-loaded',
      mappings: saved ? JSON.parse(saved) : {}
    });
  }

  // 5. API Key Storage
  if (msg.type === 'get-api-key') {
    const key = await figma.clientStorage.getAsync('gemini_api_key');
    figma.ui.postMessage({ type: 'api-key-loaded', key });
  }

  if (msg.type === 'set-api-key') {
    await figma.clientStorage.setAsync('gemini_api_key', msg.key);
  }

  // 6. Close plugin
  if (msg.type === 'cancel') {
    figma.closePlugin();
  }
};